update fix
Archiving/parallel-engine pull request #19
Opened 2019-08-07 21:34 UTC by Archiving

2019-08-07 21:47 UTC, kozr requested changes
broke entity clicking. Player::entityInTile doesn't print that entity got clicked on

2019-08-08 00:52 UTC, adrianlamcw approved these changes
Good job

2019-08-08 00:53 UTC, adrianlamcw approved these changes

2019-08-08 01:15 UTC, kozr approved these changes
The refactor looks good. Thanks so much!

2019-08-08 01:30 UTC, merged